```mermaid
graph TD
    ContentPage["ContentPage"] --> Indiko_Maui_Controls_Chat_Sample_MainPage["MainPage"]
    Shell["Shell"] --> Indiko_Maui_Controls_Chat_Sample_AppShell["AppShell"]
    Application["Application"] --> Indiko_Maui_Controls_Chat_Sample_App["App"]
    View["View"] --> Indiko_Maui_Controls_Chat_ChatView["ChatView"]
    Indiko_Maui_Controls_Chat_Sample_Services_IMessageService["IMessageService"] -.-> Indiko_Maui_Controls_Chat_Sample_Services_MessageService["MessageService"]
    ValueChangedMessage_System_DateTime_["DateTime>"] --> Indiko_Maui_Controls_Chat_Sample_Messages_HideKeyboardMessage["HideKeyboardMessage"]
    BaseViewModel["BaseViewModel"] --> Indiko_Maui_Controls_Chat_Sample_ViewModels_MainPageViewModel["MainPageViewModel"]
    ObservableObject["ObservableObject"] --> Indiko_Maui_Controls_Chat_Sample_ViewModels_BaseViewModel["BaseViewModel"]
    IViewModel["IViewModel"] -.-> Indiko_Maui_Controls_Chat_Sample_ViewModels_BaseViewModel["BaseViewModel"]
    ObservableCollection_T_["ObservableCollection<T>"] --> Indiko_Maui_Controls_Chat_Models_ObservableRangeCollection_T_["ObservableRangeCollection"]
    MauiUIApplicationDelegate["MauiUIApplicationDelegate"] --> Indiko_Maui_Controls_Chat_Sample_AppDelegate["AppDelegate"]
    MauiApplication["MauiApplication"] --> Indiko_Maui_Controls_Chat_Sample_MainApplication["MainApplication"]
    MauiAppCompatActivity["MauiAppCompatActivity"] --> Indiko_Maui_Controls_Chat_Sample_MainActivity["MainActivity"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_DateGroupSeperatorCell["DateGroupSeperatorCell"]
    UIView["UIView"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatContextMenuView["ChatContextMenuView"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OtherVideoMessageCell["OtherVideoMessageCell"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OwnAudioMessageCell["OwnAudioMessageCell"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OwnImageMessageCell["OwnImageMessageCell"]
    UICollectionViewDiffableDataSource_Indiko_Maui_Controls_Chat_Platforms_iOS_ChatSection__Indiko_Maui_Controls_Chat_Platforms_iOS_ChatMessageItem_["ChatMessageItem>"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatViewDataSource["ChatViewDataSource"]
    NSObject["NSObject"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatSection["ChatSection"]
    NSObject["NSObject"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatMessageItem["ChatMessageItem"]
    ViewHandler_ChatView__UICollectionView_["ViewHandler<ChatView, UICollectionView>"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatViewHandler["ChatViewHandler"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OwnVideoMessageCell["OwnVideoMessageCell"]
    UICollectionViewDelegateFlowLayout["UICollectionViewDelegateFlowLayout"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatViewDelegate["ChatViewDelegate"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OtherTextMessageCell["OtherTextMessageCell"]
    UICollectionViewFlowLayout["UICollectionViewFlowLayout"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_ChatViewFlowLayout["ChatViewFlowLayout"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OtherAudioMessageCell["OtherAudioMessageCell"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OwnTextMessageCell["OwnTextMessageCell"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_OtherImageMessageCell["OtherImageMessageCell"]
    UICollectionViewCell["UICollectionViewCell"] --> Indiko_Maui_Controls_Chat_Platforms_iOS_SystemMessageCell["SystemMessageCell"]
    RecyclerView_Adapter["Adapter"] --> Indiko_Maui_Controls_Chat_Platforms_Android_ChatMessageAdapter["ChatMessageAdapter"]
    RecyclerView_OnScrollListener["OnScrollListener"] --> Indiko_Maui_Controls_Chat_Platforms_Android_OnScrollListener["OnScrollListener"]
    FrameLayout["FrameLayout"] --> Indiko_Maui_Controls_Chat_Platforms_Android_BlurOverlayView["BlurOverlayView"]
    ViewHandler_ChatView__RecyclerView_["ViewHandler<ChatView, RecyclerView>"] --> Indiko_Maui_Controls_Chat_Platforms_Android_ChatViewHandler["ChatViewHandler"]
    RecyclerView_ViewHolder["ViewHolder"] --> Indiko_Maui_Controls_Chat_Platforms_Android_ChatMessageViewHolder["ChatMessageViewHolder"]
    IDisposable["IDisposable"] -.-> Indiko_Maui_Controls_Chat_Platforms_Android_ChatMessageViewHolder["ChatMessageViewHolder"]
    RecyclerView_ItemDecoration["ItemDecoration"] --> Indiko_Maui_Controls_Chat_Platforms_Android_SpacingItemDecoration["SpacingItemDecoration"]
```
