```mermaid
graph LR
    Indiko_Maui_Controls_Chat["Indiko.Maui.Controls.Chat"]
    Indiko_Maui_Controls_Chat_Models["Indiko.Maui.Controls.Chat.Models"]
    Indiko_Maui_Controls_Chat_Platforms_Android["Indiko.Maui.Controls.Chat.Platforms.Android"]
    Indiko_Maui_Controls_Chat_Platforms_iOS["Indiko.Maui.Controls.Chat.Platforms.iOS"]
    Indiko_Maui_Controls_Chat_Sample["Indiko.Maui.Controls.Chat.Sample"]
    Indiko_Maui_Controls_Chat_Sample_Interfaces["Indiko.Maui.Controls.Chat.Sample.Interfaces"]
    Indiko_Maui_Controls_Chat_Sample_Messages["Indiko.Maui.Controls.Chat.Sample.Messages"]
    Indiko_Maui_Controls_Chat_Sample_Models["Indiko.Maui.Controls.Chat.Sample.Models"]
    Indiko_Maui_Controls_Chat_Sample_Services["Indiko.Maui.Controls.Chat.Sample.Services"]
    Indiko_Maui_Controls_Chat_Sample_Utils["Indiko.Maui.Controls.Chat.Sample.Utils"]
    Indiko_Maui_Controls_Chat_Sample_ViewModels["Indiko.Maui.Controls.Chat.Sample.ViewModels"]
    Tools_CodeDocGenerator["Tools.CodeDocGenerator"]
```
